FROM nginx:alpine

# 1. Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# 2. Copy your custom config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 3. Copy SSL certificates (If you have them)
# If your folder is empty, comment these lines out to avoid errors!
# COPY ./ssl /etc/nginx/ssl