# Generated by Django 5.0.1 on 2024-09-03 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spares',
            name='date_of_purchase',
            field=models.DateField(default=datetime.date(2024, 1, 4)),
        ),
        migrations.AddField(
            model_name='spares',
            name='leadtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spares',
            name='servicelife',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spares',
            name='shelflife',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
