# Generated by Django 5.0.1 on 2024-09-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_spares_date_of_purchase_spares_leadtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueclosing',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='machineissueapproval',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='machineissuereview',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Approvel'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], max_length=50, null=True),
        ),
    ]
