# Generated by Django 3.2.15 on 2023-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='author',
        ),
        migrations.DeleteModel(
            name='Pub',
        ),
    ]
