# Generated by Django 5.0.1 on 2025-10-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_issueclosing_status_machineissueapproval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spares',
            name='category',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('hydraulic', 'Hydraulic'), ('pneumatic', 'Pneumatic'), ('safety', 'Safety'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='spares',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spares',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/'),
        ),
        migrations.AddField(
            model_name='spares',
            name='min_stock_level',
            field=models.IntegerField(default=5, help_text='Minimum stock level before low stock alert'),
        ),
    ]
