# Generated by Django 3.2.15 on 2023-07-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230722_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machines',
            name='spares',
        ),
        migrations.CreateModel(
            name='MachineSpares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machines')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.spares')),
            ],
        ),
        migrations.AddField(
            model_name='machines',
            name='machine_spare',
            field=models.ManyToManyField(blank=True, related_name='machines', through='core.MachineSpares', to='core.Spares'),
        ),
    ]
