# Generated by Django 5.0.1 on 2025-10-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_spares_category_spares_description_spares_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineissueapproval',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
