# Generated by Django 3.2.16 on 2023-08-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230727_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineissue',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.equipment'),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.machines'),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.employee'),
        ),
    ]
