# Generated by Django 5.0.1 on 2025-10-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_machineissueapproval_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineissue',
            name='operational_status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('NON_OPERATIONAL', 'Non-Operational')], default='OPERATIONAL', help_text='Is the machine operational or down?', max_length=20),
        ),
    ]
