# Generated by Django 3.2.16 on 2023-08-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230809_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machineissue',
            old_name='Images',
            new_name='image',
        ),
    ]
