# Generated by Django 5.0.1 on 2025-10-30 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fix_date_time_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spares',
            options={'ordering': ['-created_at'], 'verbose_name': 'Spare Part', 'verbose_name_plural': 'Spare Parts'},
        ),
        migrations.AddField(
            model_name='spares',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='spares',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Item manufacturer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manufacturer'),
        ),
        migrations.AddField(
            model_name='spares',
            name='manufacturer_part_number',
            field=models.CharField(blank=True, help_text='Official manufacturer part number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spares',
            name='max_stock_level',
            field=models.IntegerField(blank=True, default=100, help_text='Maximum stock level for ordering', null=True),
        ),
        migrations.AddField(
            model_name='spares',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='spares',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Review'), ('RESOLVED', 'Resolved - User Can Close'), ('AWAITING_DOCUMENTATION', 'Awaiting Engineer Documentation'), ('UNDER_OBSERVATION', 'Under Observation'), ('REVIEWED', 'Reviewed - Awaiting Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spares',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description and specifications', null=True),
        ),
        migrations.AlterField(
            model_name='spares',
            name='item_code',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spares',
            name='leadtime',
            field=models.IntegerField(blank=True, help_text='Lead time in days', null=True),
        ),
        migrations.AlterField(
            model_name='spares',
            name='name',
            field=models.CharField(help_text='Standard item name (e.g., Ball Bearing)', max_length=255),
        ),
        migrations.AlterField(
            model_name='spares',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spares',
            name='servicelife',
            field=models.IntegerField(blank=True, help_text='Service life in days', null=True),
        ),
        migrations.AlterField(
            model_name='spares',
            name='shelflife',
            field=models.IntegerField(blank=True, help_text='Shelf life in days', null=True),
        ),
        migrations.CreateModel(
            name='SpareTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Receipt - Stock In'), ('ISSUE', 'Issue - Stock Out'), ('ADJUSTMENT', 'Stock Adjustment'), ('RETURN', 'Return to Stock'), ('DAMAGE', 'Damaged/Scrapped')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Quantity moved (positive or negative)')),
                ('reason', models.TextField(help_text='Reason for transaction')),
                ('quantity_before', models.IntegerField(help_text='Stock quantity before transaction')),
                ('quantity_after', models.IntegerField(help_text='Stock quantity after transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(blank=True, help_text='Machine related to this transaction (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.machines')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.spares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, help_text='Work order/issue ticket related to this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.machineissue')),
            ],
            options={
                'verbose_name': 'Spare Transaction',
                'verbose_name_plural': 'Spare Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
