# Generated by Django 3.2.16 on 2023-08-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230815_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineissue',
            name='ticket_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
