# Generated by Django 5.0.1 on 2025-10-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_spare_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spares',
            name='item_code',
            field=models.CharField(editable=False, max_length=30, null=True, unique=True),
        ),
    ]
