# Generated by Django 5.0.1 on 2026-01-22 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_item_code_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AddField(
            model_name='machines',
            name='location',
            field=models.CharField(default='TEST', max_length=2000),
        ),
        migrations.CreateModel(
            name='MachineSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_section', to='core.machines')),
            ],
        ),
    ]
