# Generated by Django 3.2.16 on 2023-09-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_machineissue_ticket_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineissue',
            name='machine',
        ),
        migrations.AddField(
            model_name='machineissue',
            name='machine_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.machines'),
        ),
        migrations.AddField(
            model_name='machineissue',
            name='type',
            field=models.CharField(choices=[('CORRECTIVE', 'CORECTIVE'), ('PREVENTIVE', 'PREVENTIVE'), ('BREAKDOWN', 'BREAKDOWN')], default='PREVENTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.equipment'),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='image',
            field=models.ManyToManyField(to='core.ImageModel'),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MODERATE', 'MODERATE'), ('LOW', 'LOW')], default='High', max_length=50),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approvel'), ('COMPLETED', 'Approved')], default='Pending Approvel', max_length=50),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='ticket_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.employee'),
        ),
    ]
