# Generated by Django 5.0.1 on 2026-01-22 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_machines_department_machines_location_machinesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineissue',
            name='machine_section',
            field=models.ForeignKey(blank=True, help_text='Specific section of the machine affected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_issues', to='core.machinesection'),
        ),
        migrations.AddField(
            model_name='machineissue',
            name='selected_issue',
            field=models.ForeignKey(blank=True, help_text='Issue selected from master list (if available)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_issues', to='core.issuelist'),
        ),
        migrations.CreateModel(
            name='TemporaryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_description', models.TextField(help_text='User-reported issue description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Has an engineer reviewed this?')),
                ('promoted_to_issuelist', models.BooleanField(default=False, help_text='Has this been added to master IssueList?')),
                ('engineer_notes', models.TextField(blank=True, help_text='Engineer corrections/notes', null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_issues', to='core.equipment')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_issues', to='core.machines')),
                ('promoted_issue', models.ForeignKey(blank=True, help_text='Link to IssueList record if promoted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from_temp', to='core.issuelist')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_temp_issues', to='core.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temporary Issue Report',
                'verbose_name_plural': 'Temporary Issue Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='machineissue',
            name='temporary_issue',
            field=models.ForeignKey(blank=True, help_text='New issue reported by user (pending engineer review)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_issues', to='core.temporaryissue'),
        ),
    ]
