# Generated by Django 3.2.16 on 2023-09-13 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230911_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuelist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='type',
            field=models.CharField(choices=[('Corrective', 'Corrective'), ('Preventive', 'Preventive'), ('Breakdown', 'Breakdown')], default='Preventive', max_length=20),
        ),
    ]
