# Generated by Django 3.2.16 on 2023-09-13 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230913_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuelist',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
