# Generated by Django 5.0.1 on 2026-01-26 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_machineissue_machine_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuelist',
            name='user',
        ),
        migrations.AddField(
            model_name='issuelist',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Engineer who added this issue to the master list', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_issue_list_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
