# Generated by Django 5.0.1 on 2026-01-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_issuelist_user_to_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueclosing',
            name='installed_spares',
            field=models.ManyToManyField(blank=True, help_text='Spares installed during repair', related_name='used_in_repairs', to='core.spares'),
        ),
    ]
