# Generated by Django 5.0.1 on 2026-02-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_installed_spares_to_issueclosing'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineissue',
            name='closure_hours',
            field=models.FloatField(blank=True, help_text='Hours to close after documentation', null=True),
        ),
        migrations.AddField(
            model_name='machineissue',
            name='closure_timestamp',
            field=models.DateTimeField(blank=True, help_text='When complaint was officially closed', null=True),
        ),
        migrations.AddField(
            model_name='machineissue',
            name='documentation_hours',
            field=models.FloatField(blank=True, help_text='Hours to complete documentation', null=True),
        ),
        migrations.AddField(
            model_name='machineissue',
            name='documentation_timestamp',
            field=models.DateTimeField(blank=True, help_text='When engineer completed detailed documentation', null=True),
        ),
        migrations.AddField(
            model_name='machineissue',
            name='engineer_response_hours',
            field=models.FloatField(blank=True, help_text='Hours from creation to engineer quick review', null=True),
        ),
        migrations.AddField(
            model_name='machineissue',
            name='quick_review_timestamp',
            field=models.DateTimeField(blank=True, help_text='When engineer performed quick review', null=True),
        ),
        migrations.AddField(
            model_name='machineissue',
            name='total_downtime_hours',
            field=models.FloatField(blank=True, help_text='Total hours from creation to closure', null=True),
        ),
        migrations.AddField(
            model_name='machineissue',
            name='user_confirmation_timestamp',
            field=models.DateTimeField(blank=True, help_text='When user confirmed/rejected resolution', null=True),
        ),
        migrations.AddField(
            model_name='machineissue',
            name='user_response_hours',
            field=models.FloatField(blank=True, help_text='Hours from resolved to user confirmation', null=True),
        ),
        migrations.AlterField(
            model_name='spares',
            name='item_code',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
    ]
