# Generated by Django 3.2.16 on 2023-09-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineissue',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MODERATE', 'MODERATE'), ('LOW', 'LOW')], max_length=50),
        ),
    ]
