# Generated by Django 5.0.1 on 2026-02-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_machineissue_closure_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueclosing',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
