# Generated by Django 3.2.16 on 2023-10-15 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_machineissue_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineissue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approvel'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='Pending Approvel', max_length=50),
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('date_time', models.DateTimeField()),
                ('complain_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue_remarks', to='core.machineissue')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_remarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
