# Generated by Django 5.0.1 on 2024-06-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineissuereview',
            name='approvalDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
