# Generated by Django 5.0.1 on 2026-02-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_issueclosing_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineissue',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Review'), ('User Feedback', 'User Feedback'), ('RESOLVED', 'Resolved - User Can Close'), ('AWAITING_DOCUMENTATION', 'Awaiting Engineer Documentation'), ('UNDER_OBSERVATION', 'Under Observation'), ('REVIEWED', 'Reviewed - Awaiting Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], max_length=50, null=True),
        ),
    ]
