# Generated by Django 3.2.16 on 2023-10-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20231015_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineissue',
            name='type',
            field=models.CharField(choices=[('CORRECTIVE', 'Corrective'), ('PREVENTIVE', 'Preventive'), ('BREAKDOWN', 'Breakdown')], default='Preventive', max_length=20),
        ),
    ]
