# Generated by Django 5.0.1 on 2024-06-29 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_machineissuereview_approvaldate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineissuereview',
            name='approvalDate',
        ),
        migrations.CreateModel(
            name='MachineIssueApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('date_time', models.DateTimeField()),
                ('complain_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue_remarks', to='core.machineissue')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_remarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Remarks',
        ),
    ]
