# Generated by Django 5.0.1 on 2026-02-17 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_machineissue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReviewComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='EMPTY', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_review_comments', to='core.machineissue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
