# Generated by Django 5.0.1 on 2024-07-05 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_machineissuereview_approvaldate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineissuereview',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='machineissue', to='core.machineissue'),
        ),
    ]
