# Generated by Django 5.0.1 on 2026-02-19 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_quickreviewcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineissue',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'In Progress'), ('User Feedback', 'User Feedback'), ('RESOLVED', 'Resolved - User Can Close'), ('AWAITING_DOCUMENTATION', 'Awaiting Engineer Documentation'), ('UNDER_OBSERVATION', 'Under Observation'), ('REVIEWED', 'Reviewed - Awaiting Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, help_text='Hours spent working in this session', null=True)),
                ('outcome', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated'), ('UNDER_OBSERVATION', 'Under Observation')], default='IN_PROGRESS', max_length=30)),
                ('comments', models.TextField(blank=True, null=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to='core.employee')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='core.machineissue')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
