# Generated by Django 5.0.1 on 2026-02-26 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_machineissue_status_worksession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineissuereview',
            name='assignDepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.department'),
        ),
    ]
