# Generated by Django 5.0.1 on 2024-02-06 11:36

from django.db import migrations

def gen_user(apps, schema_editor):
    emp = apps.get_model('core','Employee')
    cust = apps.get_model('core','CustomUser')
    for e in emp.objects.all():
        e.user = cust.objects.get(username=e.name)
        e.save(update_fields=["user"])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_customuser_department_employee_user_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_user, reverse_code=migrations.RunPython.noop),
    ]
