# Generated by Django 5.0.1 on 2024-02-06 11:36

from django.db import migrations, models
import django.db.models.deletion
import core.models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20240206_1636'),
    ]

    operations = [
         migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=core.models.get_user, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True),
        )
    ]
