# Generated by Django 5.0.1 on 2026-02-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_machineissuereview_assigndepartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machineissuereview',
            old_name='reviewrImages',
            new_name='reviewerImages',
        ),
    ]
