# Generated by Django 5.0.1 on 2024-02-09 11:45

from django.db import migrations




def create_group_permission(apps, schema_editor):

    #import models 
    ContentType = apps.get_model('contenttypes', 'ContentType')
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    content_type = ContentType.objects.get_for_model(User)

    #create groups
    user, created = Group.objects.get_or_create(name='User')
    engineer, created = Group.objects.get_or_create(name='engineer')
    approver, created = Group.objects.get_or_create(name='approver')

    #create permissions
    
    #User level Permissions
    create_complain_perm, created = Permission.objects.get_or_create(
        codename = 'can_create_complain',
        name = 'Can Create Complain',
        content_type = content_type,
    
    ) 

    view_complain_status, created = Permission.objects.get_or_create(
        codename = 'can_view_complain_status',
        name = 'Can View Complain Status',
        content_type = content_type,
    )


    #Engineer Level Permissions
    
    view_complain_history, created = Permission.objects.get_or_create(
        codename = 'can_view_complain_history',
        name = 'Can View Complain History',
        content_type = content_type,
    )

    edit_complain_status, created = Permission.objects.get_or_create(
        codename = 'can_edit_complain_history',
        name = 'Can Edit Complain History',
        content_type = content_type,
    )


    # MORE TO BE DEFINED LATER

    #APPROVER LEVEL PERMISSIONS
    #TO BE DEFINED LATER


    user.permissions.add(create_complain_perm, view_complain_status)
    engineer.permissions.add(create_complain_perm, view_complain_status, view_complain_history, edit_complain_status)
    approver.permissions.add(create_complain_perm, view_complain_status, view_complain_history, edit_complain_status)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20240206_1636'),
    ]

    operations = [
        migrations.RunPython(create_group_permission),
    ]
