# Generated by Django 5.0.1 on 2026-10-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_reviewrimages_machineissuereview_reviewerimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineissue',
            options={'permissions': [('view_all_issues', 'Can view all issues'), ('view_own_issues', 'Can view own raised issues')]},
        ),
    ]
