# Generated by Django 5.0.1 on 2026-10-08 05:10

from django.db import migrations

# Which groups get which dashboard visibility permission
GROUP_PERMISSIONS = {
    'Engineers': ['view_all_issues'],
    'admin': ['view_all_issues'],
    'User': ['view_own_issues'],
}

PERMISSION_NAMES = {
    'view_all_issues': 'Can view all issues',
    'view_own_issues': 'Can view own raised issues',
}


def assign_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Permissions are normally created after all migrations run (post_migrate),
    # so create them here to be able to attach them to groups now.
    content_type, _ = ContentType.objects.get_or_create(app_label='core', model='machineissue')
    permissions = {}
    for codename, name in PERMISSION_NAMES.items():
        permissions[codename], _ = Permission.objects.get_or_create(
            codename=codename, content_type=content_type, defaults={'name': name},
        )

    for group_name, codenames in GROUP_PERMISSIONS.items():
        group, _ = Group.objects.get_or_create(name=group_name)
        group.permissions.add(*(permissions[c] for c in codenames))


def remove_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    permissions = Permission.objects.filter(
        content_type__app_label='core', codename__in=PERMISSION_NAMES.keys(),
    )
    for group in Group.objects.filter(name__in=GROUP_PERMISSIONS.keys()):
        group.permissions.remove(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_machineissue_view_permissions'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(assign_permissions, remove_permissions),
    ]
