# Generated by Django 5.0.1 on 2024-02-14 11:01

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20240209_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineissue',
            name='problem_nature',
            field=models.CharField(choices=[('ELECTRICAL', 'Electrical'), ('MECHANICAL', 'Mechanical'), ('HYDRAULIC', 'Hydraulic')], default='Electrical', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
    ]
