# Generated by Django 5.0.1 on 2024-02-14 12:17

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_machineissue_problem_nature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineissue',
            name='department',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.PROTECT, to='core.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
    ]
