# Generated by Django 5.0.1 on 2026-10-08 11:01

from django.db import migrations

# Groups that may see machines of every department
GROUPS_WITH_ALL_MACHINES = ['Engineers', 'admin']


def assign_permission(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Permissions are normally created after all migrations run (post_migrate),
    # so create it here to be able to attach it to groups now.
    content_type, _ = ContentType.objects.get_or_create(app_label='core', model='machines')
    permission, _ = Permission.objects.get_or_create(
        codename='view_all_machines', content_type=content_type,
        defaults={'name': 'Can view machines of all departments'},
    )
    for group_name in GROUPS_WITH_ALL_MACHINES:
        group, _ = Group.objects.get_or_create(name=group_name)
        group.permissions.add(permission)


def remove_permission(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    permission = Permission.objects.filter(content_type__app_label='core', codename='view_all_machines').first()
    if permission:
        for group in Group.objects.filter(name__in=GROUPS_WITH_ALL_MACHINES):
            group.permissions.remove(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_assign_issue_view_permissions'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machines',
            options={'permissions': [('view_all_machines', 'Can view machines of all departments')]},
        ),
        migrations.RunPython(assign_permission, remove_permission),
    ]
