# Generated by Django 5.0.1 on 2024-02-14 12:23

import core.models
import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_machineissue_department_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dpt_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='department',
            field=models.ForeignKey(default=core.models.get_department, on_delete=django.db.models.deletion.PROTECT, to='core.department'),
        ),
    ]
