# Generated by Django 5.0.1 on 2024-02-14 12:27

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_department_dpt_type_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dpt_type',
            field=models.CharField(blank=True, choices=[('SERVICES', 'SERVICES'), ('PRODUCTION', 'PRODUCTION'), ('MAINTENANC', 'MAINTENANCE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
    ]
