# Generated by Django 5.0.1 on 2024-02-15 11:09

import core.models
import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_department_dpt_type_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineissue',
            name='assign_person',
            field=models.ForeignKey(default=core.models.get_employee, on_delete=django.db.models.deletion.PROTECT, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
    ]
