# Generated by Django 5.0.1 on 2024-02-19 12:49

import core.fields
import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_machineissue_assign_person_alter_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', core.fields.UnitIDField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
    ]
