# Generated by Django 5.0.1 on 2024-02-21 11:17

import core.models
import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='Location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='department',
            name='unit',
            field=models.ForeignKey(default=core.models.get_unit, on_delete=django.db.models.deletion.PROTECT, to='core.unit'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
    ]
