# Generated by Django 5.0.1 on 2024-03-05 06:25

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_location_unit_location_department_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='machine_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
    ]
