# Generated by Django 5.0.1 on 2024-03-12 09:22

import core.models
import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_machines_machine_hours_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='assign_person',
            field=models.ForeignKey(blank=True, default=core.models.get_employee, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='priority',
            field=models.CharField(blank=True, choices=[('HIGH', 'High'), ('MODERATE', 'MODERATE'), ('LOW', 'LOW')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='problem_nature',
            field=models.CharField(blank=True, choices=[('ELECTRICAL', 'Electrical'), ('MECHANICAL', 'Mechanical'), ('HYDRAULIC', 'Hydraulic')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Approvel'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='Pending Approvel', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='type',
            field=models.CharField(blank=True, choices=[('CORRECTIVE', 'Corrective'), ('PREVENTIVE', 'Preventive'), ('BREAKDOWN', 'Breakdown'), ('CALIBRATION', 'Calibration')], default='Preventive', max_length=20, null=True),
        ),
    ]
