# Generated by Django 5.0.1 on 2024-03-18 10:13

import core.models
import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_description_machineissue_description_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineissue',
            name='assign_person',
        ),
        migrations.RemoveField(
            model_name='machineissue',
            name='code',
        ),
        migrations.RemoveField(
            model_name='machineissue',
            name='department',
        ),
        migrations.RemoveField(
            model_name='machineissue',
            name='description_reviewer',
        ),
        migrations.RemoveField(
            model_name='machineissue',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='machineissue',
            name='problem_nature',
        ),
        migrations.RemoveField(
            model_name='machineissue',
            name='type',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='machineissue',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Approvel'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='MachineIssueReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_reviewer', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('HIGH', 'High'), ('MODERATE', 'MODERATE'), ('LOW', 'LOW')], max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('CORRECTIVE', 'Corrective'), ('PREVENTIVE', 'Preventive'), ('BREAKDOWN', 'Breakdown'), ('CALIBRATION', 'Calibration')], max_length=20, null=True)),
                ('problemNature', models.CharField(blank=True, choices=[('ELECTRICAL', 'Electrical'), ('MECHANICAL', 'Mechanical'), ('HYDRAULIC', 'Hydraulic')], max_length=50, null=True)),
                ('reviewDate', models.DateTimeField(auto_now=True)),
                ('assignDepartment', models.ForeignKey(default=core.models.get_department, on_delete=django.db.models.deletion.PROTECT, to='core.department')),
                ('assignPerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assigned', to='core.employee')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.issuelist')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machineissue')),
                ('reviewrImages', models.ManyToManyField(to='core.imagemodel')),
                ('reviwer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='core.employee')),
            ],
        ),
    ]
