# Generated by Django 5.0.1 on 2024-03-19 05:43

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machineissuereview',
            old_name='reviwer',
            new_name='reviewer',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
    ]
